# Generated by Django 5.2.5 on 2025-08-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sisgeac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aluno',
            table='aluno',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='curso',
        ),
        migrations.AlterModelTable(
            name='disciplina',
            table='disciplina',
        ),
        migrations.AlterModelTable(
            name='falta',
            table='falta',
        ),
        migrations.AlterModelTable(
            name='matricula',
            table='matricula',
        ),
        migrations.AlterModelTable(
            name='turma',
            table='turma',
        ),
    ]
