# Generated by Django 5.2.5 on 2025-08-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sisgeac', '0002_alter_aluno_table_alter_curso_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nota',
            table='nota',
        ),
    ]
