# Generated by Django 5.2.5 on 2025-08-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sisgeac', '0003_alter_nota_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['nome'], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
    ]
