# Generated by Django 5.2.5 on 2025-08-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sisgeac', '0004_alter_professor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['nome'], 'verbose_name': 'Professor'},
        ),
    ]
