# Generated by Django 5.2.5 on 2025-08-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sisgeac', '0006_alter_professor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Aluno'},
        ),
    ]
