# Generated by Django 5.2.5 on 2025-08-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sisgeac', '0007_alter_aluno_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Sobrenome'),
        ),
    ]
