# Generated by Django 5.2.5 on 2025-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sisgeac', '0008_aluno_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Sobrenome'),
        ),
    ]
