# Generated by Django 5.2.5 on 2025-08-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sisgeac', '0009_professor_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='last_name',
            new_name='sobrenome',
        ),
    ]
