# Generated by Django 5.2.5 on 2025-08-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sisgeac', '0010_rename_last_name_aluno_sobrenome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='last_name',
            new_name='sobrenome',
        ),
    ]
