# Generated by Django 5.2.5 on 2025-08-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sisgeac', '0011_rename_last_name_professor_sobrenome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='ativo',
            new_name='status',
        ),
    ]
