# Generated by Django 5.2.5 on 2025-08-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sisgeac', '0012_rename_ativo_aluno_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='ativo',
            new_name='status',
        ),
    ]
