# Generated by Django 5.2.5 on 2025-08-25 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sisgeac', '0013_rename_ativo_professor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno', to='Sisgeac.curso'),
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='professores', to='Sisgeac.disciplina'),
        ),
    ]
