"""
Django settings for Sistema_Gestao_Academica project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l)b-$^pbf6k(&o&k5rqm#+&m1qw#(sm+yqqyg8=-kk0*@nb+!#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "Sisgeac.apps.SisgeacConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Sistema_Gestao_Academica.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Sistema_Gestao_Academica.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sigeac',
        'USER': 'root',
        'PASSWORD': '8523.Jesus',
        'HOST': '127.0.0.1',
        'PORT': '3308',
    }
}

JAZZMIN_SETTINGS = {
    "site_title": "Painel Administrativo",
    "site_header": "Administração do Sistema",
    "site_brand": "Sisgeac",
    "welcome_sign": "Login",

    "show_sidebar": True,
    "navigation_expanded": True,
    
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "Sisgeac"},
    ],
    

    # Ícones para cada model
    "icons": {
        "auth.User": "fas fa-user-shield",
        "auth.Group": "fas fa-users-cog", 
        "Sisgeac.Aluno": "fas fa-user-graduate",
        "Sisgeac.Professor": "fas fa-chalkboard-teacher",
        "Sisgeac.Curso": "fas fa-book",
        "Sisgeac.Disciplina": "fas fa-book-open",
        "Sisgeac.Turma": "fas fa-users",
        "Sisgeac.Matricula": "fas fa-id-card",
        "Sisgeac.Nota": "fas fa-clipboard-check",
        "Sisgeac.Falta": "fas fa-user-times",
    },

    # Ícones padrões
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",

    # Ordem dos apps no menu
    "order_with_respect_to": ["auth", "Sisgeac"],

    # Se quiser colocar logo personalizado:
    "site_logo": "imagens/sisgeac.webp",
    "login_logo": "imagens/sisgeac.webp",
    
    "custom_css": "css/custom.css",

}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / "static"]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
